version: '3'
services:
  rails:
    build: ./rails
    container_name: rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./rails:/app_name
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql